name: Bug report
description: Create a report to help us improve
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened? What did you expect to happen?
      placeholder: Clear and concise description
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide steps or a minimal reproduction
      placeholder: 1) ... 2) ... 3) ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
      placeholder: e.g. luna-proxy-web v0.1.0 or commit SHA
  - type: dropdown
    id: area
    attributes:
      label: Area
      multiple: true
      options:
        - Web (luna-proxy-web)
        - API (luna-proxy-api)
        - Docs
        - CI/CD
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs, errors, or screenshots
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I searched existing issues
          required: true
        - label: I can help with a PR
          required: false