blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/luna-assistant-ai/ai-gate/security/policy
    about: Please report security vulnerabilities via our SECURITY.md