name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: luna-proxy-web/package-lock.json
      - name: Install deps (web)
        working-directory: luna-proxy-web
        run: npm ci --no-audit --no-fund
      - name: Validate (type-check + lint + tests)
        working-directory: luna-proxy-web
        run: npm run validate