name: DCO
on:
  pull_request:
    branches: [ main ]
jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DCO Check
        uses: tim-actions/dco@v1.3.1
        with:
          require_branch_sign_off: false